---@type LazyPluginSpec
return {
  "astroui",
  ---@param opts AstroUIOpts
  opts = function(_, opts)
    opts.icons = {
      ActiveLSP = "",
      ActiveTS = "",
      ArrowLeft = "",
      ArrowRight = "",
      Bookmarks = "",
      BufferClose = "",
      DapBreakpoint = "",
      DapBreakpointCondition = "",
      DapBreakpointRejected = "",
      DapLogPoint = "󱞪",
      DapStopped = "󰁕",
      Debugger = "",
      DefaultFile = "󰈙",
      Diagnostic = "󰒡",
      DiagnosticError = "E",
      DiagnosticHint = "?",
      DiagnosticInfo = "i",
      DiagnosticWarn = "W",
      Ellipsis = "…",
      Environment = "",
      Exit = "",
      FileModified = "",
      FileNew = "",
      FileReadOnly = "",
      FoldClosed = "",
      FoldOpened = "",
      FoldSeparator = " ",
      FolderClosed = "",
      FolderEmpty = "",
      FolderOpen = "",
      Git = "󰊢",
      GitAdd = "+",
      GitBranch = "",
      GitChange = "~",
      GitConflict = "!",
      GitDelete = "-",
      GitIgnored = "*",
      GitRenamed = "R",
      GitSign = "┃",
      GitStaged = "S",
      GitUnstaged = "U",
      GitUntracked = "?",
      LSPLoading1 = "⠲",
      LSPLoading2 = "⠴",
      LSPLoading3 = "⠦",
      LSPLoading4 = "⠖",
      MacroRecording = "",
      Paste = "󰅌",
      Refresh = "",
      ScrollText = "",
      Search = "",
      Selected = "❯",
      Session = "󰓅",
      Prompt = "➤",
      Setting = "",
      Sort = "󰒺",
      Spellcheck = "󰓆",
      Tab = "󰓩",
      TabClose = "󰅙",
      Terminal = "",
      Tree = "",
      VimIcon = "",
      Window = "󱂬",
      WordFile = "󰈭",
    }
  end,
}
